services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: donations
      DB_USER: root
      DB_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:9.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: donations
      MYSQL_USER: pmk
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
